#########################
# Static tool & environment definition paths
#########################
home_dir:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/Ardetype/
work_dir:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/Ardetype/data/
databases:
  /mnt/beegfs2/home/groups/nmrl/db/
status_script_path:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/Ardetype/subscripts/pbs-status.py
ardetype_version:
  v0.1.0-dev
aquamis_qc_reference: 
  /mnt/beegfs2/home/groups/nmrl/db/AQUAMIS_thresholds.json


##############
# bact_core
##############
kraken2_env_path:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/Ardetype/.snakemake/conda/2a1a64fdbb7d92bc497cb7b9567b6099
kraken2_env:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/Ardetype/config_files/conda_defs/kraken2.yaml
krona_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/krona.sif
shovill_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/shovill.sif
fastp_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/fastp.sif

##############
# bact_shell
##############
amrfinderplus_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/ncbi-amrfinderplus_latest.sif
amrpp_repo:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/amrplusplus_v2/
hamronization_sif:
  /mnt/home/jevgen01/nmrl_bgfs/image_files/hamronization_latest.sif
mlst_quast_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/mlst_quast.sif
mob_suite_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/mob_suite_3.0.3.sif
nextflow_env:
  /mnt/home/groups/nmrl/bact_analysis/Ardetype/config_files/conda_defs/nextflow.yaml
resfinder_sif:
  /mnt/home/groups/nmrl/image_files/resfinder_4.1.11.sif
rgi_env_path:
  /mnt/home/jevgen01/nmrl/bact_analysis/Ardetype/.snakemake/conda/90ebab03d6f8768a17d9bd8f7bf21eac
rgi_env:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/Ardetype/config_files/conda_defs/rgi_env.yaml
hamronization_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/hamronization_latest.sif
resfinder_version: resfinder_v4.1.11
resfinder_db_version: resfinder_2023-03-29
rgi_version: rgi_v5.2.1
rgi_db_version: card_v3.1.4
amrplusplus_version: amrplusplus_v2.0
amrplusplus_db_version: MEGARES
amrfinderplus_version: 3.10.42
amrfinderplus_db_version: 2022-10-11.2




##############
# bact_tip
##############
agrvate_saureus_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/agrvate_saureus.sif
emmtyper_spyogenes_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/emmtyper_spyogenes.sif
hicap_hinfluenzae_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/hicap_hinfluenzae.sif
kleborate_kpneumoniae_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/kleborate_kpneumoniae.sif
legsta_lpneumophila_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/legsta_lpneumophila.sif
lissero_lmonocytogenes_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/lissero_lmonocytogenes.sif
lpgenomics_repo:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/legionella_pneumophila_genomics/
meningotype_nmeningitidis_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/meningotype_nmeningitidis.sif  
sccmec_saureus_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/sccmec_saureus.sif
seqsero2_senterica_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/seqsero2_senterica.sif
sistr_senterica_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/sistr_senterica.sif
spatyper_saureus_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/spatyper_saureus.sif
ectyper_ecoli_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/ectyper_ecoli.sif
seroba_spneumoniae_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/seroba_spneumoniae.sif
seroba_spneumoniae_database:
  /mnt/beegfs2/home/groups/nmrl/db/db-seroba
pigz_sif:
  /mnt/beegfs2/home/groups/nmrl/bact_analysis/legionella_pneumophila_genomics/image_files/pigz_latest.sif
stecfinder_ecoli_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/stecfinder_ecoli.sif
lrefinder_efaecium_efaecalis_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/lre_finder.sif
lrefinder_database:
  /mnt/beegfs2/home/groups/nmrl/db/db-lrefinder


##############
# bact_shape
##############
multiqc_sif:
  /mnt/beegfs2/home/groups/nmrl/image_files/fastq_screen.sif


#########################
# bact_core configuration
#########################

###Filled by the wrapper
core_input_files:
core_target_files:
output_directory:

#####################
# Configuration notes
#####################
# Tools that use contigs as input may perform differently (or fail) if short contigs (shovull minlen option) are included (excluded) from the assembly or read correction module is turned on/off.
# For example, Sequence-Based-Typing with legsta for Legionella pneumophila will need all contigs to determine sequence type (ST) - shovill minlen 1.
# On the other hand, Pasteur and Pubmlst database APIs will only accept assemblies that contain less than 5000 contings in total, so shovill minlen should be changed accordingly.
# Serogroup detection for Listeria monocytogenes by lissero will fail, if blast will not be able to identify any matches in the contigs, which is guaranteed to happen if contigs are from another species
# but may also happen if contigs do not cover regions of interest (e.g. sequencing failed on genes required by the tool).

core_tool_configs:
  kraken2:
    threads: 12
    human_db: /mnt/beegfs2/home/groups/nmrl/db/db-kraken2/human_reference/
    ram_host_mb: 262144
    bact_db: /mnt/beegfs2/home/groups/nmrl/bact_analysis/AQUAMIS/reference_db/kraken
    # /mnt/beegfs2/home/groups/nmrl/db/db-kraken2/full_ref_bafp/
    # /mnt/beegfs2/home/groups/nmrl/bact_analysis/AQUAMIS/reference_db/kraken
    # 
    ram_bact_mb: 262144
    #24576
  shovill:
    minlen: 1
    mincov: 0 #2
    cpus: 35
    ram: 100
    depth: 100
    modules: --noreadcorr
  fastp:
    max_len1: 0 #trim bases after given length in read1
    max_len2: 0 #trim bases after given length in read2

#########################
# bact_shell configuration
#########################

###Filled by the wrapper
shell_input_files:
shell_target_files:
shell_tool_configs:
#Configuration settings for each tool used by bact_shell snakefile
  amr_plusplus:
    threads: 24
  amrfinderplus_species:
    - Acinetobacter_baumanniiae
    - Burkholderia_cepaciaae
    - Burkholderia_pseudomalleiae
    - Campylobacterae
    - Clostridioides_difficileae
    - Enterococcus_faecalisae
    - Enterococcus_faeciumae
    - Escherichiaae
    - Klebsiellaae
    - Neisseriaae
    - Pseudomonas_aeruginosaae
    - Salmonellaae
    - Staphylococcus_aureusae
    - Staphylococcus_pseudintermediusae
    - Streptococcus_agalactiaeae
    - Streptococcus_pneumoniaeae
    - Streptococcus_pyogenesae
    - Vibrio_cholerae
  resfinder:
    length: 0.6
    coverage: 0.9
    resfinder_db: /mnt/beegfs2/home/groups/nmrl/db/db-resfinder/ #pointfinder db contained within
    pointfinder_species:
      - campylobacter jejuni
      - campylobacter coli
      - salmonella enterica
      - escherichia coli
      - enterococcus faecalis
      - enterococcus faecium
      - helicobacter pylori
      - klebsiella pneumoniae
      - staphylococcus aureus
  plasmidfinder:
    plasmidfinder_sif: /mnt/beegfs2/home/groups/nmrl/image_files/plasmidfinder_latest.sif
    plasmidfinder_db: /mnt/beegfs2/home/groups/nmrl/db/plasmidfinder_db/
  virulencefinder:
    virulencefinder_sif: /mnt/beegfs2/home/groups/nmrl/image_files/virulencefinder.sif
    virulencefinder_db: /mnt/beegfs2/home/groups/nmrl/db/virulencefinder_db/
  rmlst_pubmlst:
    schema: http://rest.pubmlst.org/db/pubmlst_rmlst_seqdef_kiosk/schemes/1/sequence
    api_seq_limit: 5000



#########################
# bact_tip configuration
#########################

###Filled by the wrapper
tip_input_files:
tip_target_files:
tip_tool_configs:
#Configuration settings for each tool used by bact_tip snakefile
  agrvate_saureus:
  emmtyper_spyogenes:
  hicap_hinfluenzae:
  kaptive_kpneumoniae:
  kleborate_kpneumoniae:
  legsta_lpneumophila:
  lissero_lmonocytogenes:
  lpgenomics_lpneumophila:
  meningotype_nmeningitidis:
  pasteurmlst_lmonocytogenes:
  publmst_ngonorrhoe:
  sccmec_saureus:
  seqsero_senterica:
    threads: 16
  sistr_senterica:
  spatyper_saureus:
  ectyper_ecoli:
  seroba_spneumoniae:
  cgmlstfinder:
    cgmlstfinder_sif: /mnt/beegfs2/home/groups/nmrl/image_files/cgmlstfinder.sif
    cgmlstfinder_db: /mnt/beegfs2/home/groups/nmrl/db/cgmlstfinder_db/
    cgmlstfinder_orgs:
      salmonella: salmonella
      escherichia coli: ecoli
      baumannii: abaumannii
      streptococcus pneumoniae: spneumoniae
      streptococcus pyogenes: streptococcus
      campylobacter: campylobacter
      clostridium: clostridium
  chewbbaca:
    chewbbaca_sif: /mnt/beegfs2/home/groups/nmrl/image_files/chewbacca_cgmlst.sif
    chewbbaca_cores: 12
    chewbbaca_orgs:
      salmonella: 
        db: Salmonella_enterica
        version: 2.0
        origin: https://www.cgmlst.org/ncs/schema/4792159/
        allele_count: 3001
      escherichia coli: 
        db: Escherichia_coli
        version: 1.0
        origin: https://www.cgmlst.org/ncs/schema/5064703/
        allele_count: 2513
      baumannii: 
        db: Acinetobacter_baumannii
        version: 1.0
        origin: https://www.cgmlst.org/ncs/schema/3956907/
        allele_count: 2390
      streptococcus pyogenes: 
        db: spyogenes_wgMLST
        version: '2021-07-27'
        origin: https://chewbbaca.online/species/1
        allele_count: 3044
      campylobacter: 
        db: Campylobacter_jejuni_coli
        version: '2023-05-03'
        origin: https://www.cgmlst.org/ncs/schema/145039/
        allele_count: 637
      klebsiella: 
        db: Klebsiella_pneumoniae_variicola_quasipneumoniae
        version: 1.0
        origin: https://www.cgmlst.org/ncs/schema/2187931/
        allele_count: 2358
      legionella: 
        db: Legionella_pneumophila
        version: 1.1
        origin: https://www.cgmlst.org/ncs/schema/1025099/
        allele_count: 1521
      listeria: 
        db: Listeria_monocytogenes
        version: 2.1
        origin: https://www.cgmlst.org/ncs/schema/690488/
        allele_count: 1701
      staphylococcus aureus: 
        db: Staphylococcus_aureus
        version: 1.3
        origin: https://www.cgmlst.org/ncs/schema/141106/
        allele_count: 1861
      pseudomona: 
        db: Pseudomonas_aeruginosa_cgMLST
        version: 1.0
        origin: https://www.cgmlst.org/ncs/schema/16115339/
        allele_count: 3867
      enterococcus faecalis: 
        db: Enterococcus_faecalis_cgMLST
        version: 1.0
        origin: https://www.cgmlst.org/ncs/schema/3887469/
        allele_count: 1972
      enterococcus faecium: 
        db: Enterococcus_faecium_cgMLST
        version: 1.1
        origin: https://www.cgmlst.org/ncs/schema/991893/
        allele_count: 1423
      yersinia: 
        db: Yersinia.cgMLSTv1_chewbbaca
        version: '2023-08-16'
        origin: https://enterobase.warwick.ac.uk/schemes/Yersinia.cgMLSTv1/
        allele_count: 1553
      clostridioides: 
        db: Clostridioides_difficile_db
        version: 2.0
        origin: https://www.cgmlst.org/ncs/schema/12556067/
        allele_count: 2147
  lrefinder_efaecium_efaecalis:
    id: 80

  

#########################
# bact_shape configuration
#########################
shape_input_files:
shape_target_files:
shape_tool_configs: